title: Test
email: test@gmail.com
description: Mel Sayre's personal website
baseurl: ""
url: "http://www.melsayre.com"
twitter_username: priscorum
github_username:  melsayre

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-gallery-generator
exclude:
  - Gemfile
  - Gemfile.lock

gallery:
  dir: prints               # Path to the gallery
  symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "Gallery"           # Title for gallery index page
  title_prefix: "Gallery: "  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field: "date_time"   # How to sort galleries on the index page.
                            # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: 400                  # max width of thumbnails (in pixels)
    y: 400                  # max height of thumbnails (in pixels)