title: Test
email: test@gmail.com
description: Mel Sayre's personal website
baseurl: ""
url: "http://www.melsayre.com"
twitter_username: priscorum
github_username:  melsayre

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-gallery-generator
exclude:
  - Gemfile
  - Gemfile.lock