title: Mel Sayre - Home
email: priscorum@gmail.com
description: Mel Sayre's personal website
baseurl: ""
url: ""
twitter_username: priscorum
github_username:  melsayre

exclude:
  - Gemfile
  - Gemfile.lock
